### PR TITLE
cd when `HOME` is not set or empty

### LINKED ISSUE #119: cd when `HOME` is not set or empty
```
bash-3.2$ unset HOME
bash-3.2$ cd
bash: cd: HOME not set
```
```
✔︎ minishell > unset HOME
✔︎ minishell > cd
minishell: cd: : Bad address
```
----
```
bash-3.2$ cd Desktop/
bash-3.2$ HOME=
bash-3.2$ cd
bash-3.2$ pwd
/Users/tchoquet/Desktop
```
```
✔︎ minishell > cd Desktop/
✔︎ minishell > HOME=
✔︎ minishell > cd
minishell: cd: : No such file or directory
✘ minishell > pwd
/Users/tchoquet/Desktop
```

### PR DESCRIPTION
**Pull request by jizots**
Fixes #119 add norm fix in here_doc

### CODE REVIEW

**Review by Thomas-Chqt — CHANGES_REQUESTED** [review]
when `HOME` is not set, doing `cd ~` still print a error
```
bash-3.2$ unset HOME
bash-3.2$ cd ~
```

```
✔︎ minishell > unset HOME
✔︎ minishell > cd ~
minishell: cd: : No such file or directory
```

i think you should not do anything when the argument of cd is an empty string

you also need to not change `OLDPWD` when `HOME` is not set 

```
bash-3.2$ cd Desktop/
bash-3.2$ echo $PWD
/Users/tchoquet/Desktop
bash-3.2$ echo $OLDPWD
/Users/tchoquet
bash-3.2$ unset HOME
bash-3.2$ cd
bash: cd: HOME not set
bash-3.2$ echo $PWD
/Users/tchoquet/Desktop
bash-3.2$ echo $OLDPWD
/Users/tchoquet
```

```
✔︎ minishell > cd Desktop/
✔︎ minishell > echo $PWD
/Users/tchoquet/Desktop
✔︎ minishell > echo $OLDPWD
/Users/tchoquet
✔︎ minishell > unset HOME
✔︎ minishell > cd
minishell: cd: HOME not set
✘ minishell > echo $PWD
/Users/tchoquet/Desktop
✔︎ minishell > echo $OLDPWD
/Users/tchoquet/Desktop
```

**Comment by jizots** [comment]
Why cmd ~ can not print?
So, I cant get `~` to compare.
I think it's lexser or expander's problem.
```
✘ minishell > cat ~
cat: : No such file or directory
✘ minishell > cat "~"
cat: ~: No such file or directory
```
```
bash-5.2$ cat ~
cat: /Users/hotph: Is a directory
(rc->1)
bash-5.2$ cat "~"
cat: ~: No such file or directory
(rc->1)
```

**Comment by Thomas-Chqt** [comment]
it is working for me
```
✔︎ minishell > cat ~
cat: /Users/tchoquet: Is a directory
✘ minishell > cat "~"
cat: ~: No such file or directory
```

are you sure `HOME` is set in your minishell ?

`~` is juste the same as `$HOME`

**Comment by jizots** [comment]
I can same execution. thank you

**Pull request closed without merging**
