### PR TITLE
Jizots/issue134

### PR DESCRIPTION
**Pull request by jizots**
So, sorry. It's my mistake.

### CODE REVIEW

**Review by Thomas-Chqt — CHANGES_REQUESTED** [review]
Leak is gone but,
in bash when you do `cd` inside a folder with chmod 000 there is no error.
I think this because you use the `getcwd` system call to set the `OLDPWD` environment variable,
if you use `PWD` to set `OLDPWD` the error will disappeare.

**Review by Thomas-Chqt — APPROVED** [review]
this cause a crash :

```
✔︎ minishell > mkdir test
✔︎ minishell > cd test/
✔︎ minishell > chmod 000 .
✔︎ minishell > pwd
```

**Review by Thomas-Chqt — CHANGES_REQUESTED** [review]
this cause a crash :

```
✔︎ minishell > mkdir test
✔︎ minishell > cd test/
✔︎ minishell > chmod 000 .
✔︎ minishell > pwd
```

**Review by Thomas-Chqt — CHANGES_REQUESTED** [review]
when doing `cd ..` in a folder under chmod 000, no error should be printed.
in minishell, error `minishell: cd: ..: No such file or directory` is printed.
i think this is because you do cd on the .. folder, you sould to a cd on the `OLDPWD`

**Comment by Thomas-Chqt** [comment]
i can't change user authorizations on my computer, even if i do chmod 000 the folder stay `drwx------`.
so i cant really try for now

**Comment by jizots** [comment]
OK. 
Maybe, you can use minus option `chmod -w -r -x testdir`

**Comment by Thomas-Chqt** [comment]
no, idk why i can't, i can on files but not on directories.
try a lot of test case on your side and i will merge it on Saturday when i go to 42

**Comment by Thomas-Chqt** [comment]
`pwd` fail when PWD is not set, i think you should do : `getcwd()` and only if it fail, use PWD, but i can try inside a folder without read access so idk what's happened in bash, the only thing is can see is that `pwd` work in bash when PWD is not set

**Comment by jizots** [comment]
I changed code. Now after unset PWD, can use pwd.
But, after additional entry ` chmod 000 . ` , can't work pwd.
bash is working above case. So, bash has another data for CWD out of env.

I don't intend to respond to that, but do you really want to?

**Comment by Thomas-Chqt** [comment]
no i think we dont need to do it.
i will come early on Saturday to try with `chmod 000 .` and i merge it.
お疲れ様です

**Comment by Thomas-Chqt** [comment]
minishell crash when doing `cd ..` after setting PWD and OLDPWD to empty string
it crash even in a folder with normal permissions

```
✔︎ minishell > cd 
✔︎ minishell > cd Desktop/
✔︎ minishell > pwd
/Users/tchoquet/Desktop
✔︎ minishell > PWD=
✔︎ minishell > OLDPWD=
✔︎ minishell > env | grep PWD
PWD=
OLDPWD=
✔︎ minishell > cd ..
```

**Comment by Thomas-Chqt** [comment]
> minishell crash when doing `cd ..` after setting PWD and OLDPWD to empty string
it crash even in a folder with normal permissions

> ```
✔︎ minishell > cd 
✔︎ minishell > cd Desktop/
✔︎ minishell > pwd
/Users/tchoquet/Desktop
✔︎ minishell > PWD=
✔︎ minishell > OLDPWD=
✔︎ minishell > env | grep PWD
PWD=
OLDPWD=
✔︎ minishell > cd ..
```
 

in the function `curtail_str_by_char()` you use `ft_strrchr()` but you dont check if the result is not NULL, if `ft_strrchr()` dont find the character it return NULL

**Review by Thomas-Chqt — APPROVED** [review]

**Pull request merged**
